[build]
  base = "client"
  command = "npm install && npm run build -w client"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 